                    <div class="row contenido">

                        <div class="col-12 rounded shadow-sm rounded pb-5">
                            
                            <h1 class="py-3 text-center">Horario de Aulas y Laboratorios 2024-2</h1>
                            <p class="py-3 text-center">
                                Actualización 07/05/2024 21:20 p.m.
                            </p>
                            <div class="row">
                                <div class="col-md-6 mx-auto">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Edificio D</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1HJ9-HA0FlYXFrI350r9B8Gv5EWHEajFq/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            D107
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1L-gHqyDag0By7wP01BPfi_c8QQ7HaO4X/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            D108
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1pfMEJZHWHI7p0prF1wX_o85KPVp2JTot/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            D109
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/13ku-9cy3PRM7wAK6FmLrS-PQ4chu2DpU/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            D110
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/10eAXSZjNlzwRHKbs03pQ35kuQiKMdoxs/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            D203
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <div class="col-md-6 mx-auto">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Edificio CCAI</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/12AUU7e3dSS2fKrbJHjo14_fWigQhC2GY/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            CCAI Lab PC
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1hY4_IW7Bz5DGmHz3ftgqDObgNvDuVHch/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            CCAI Lab Mac
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <div class="col-md-6 mx-auto">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Edificio M</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1K710Hsh3-b0nolFIFNajcyS_arr_dq7X/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            M201
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/10ROg8zFhqiCi51P3_jIn_16t51oXHRbR/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            M205
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1f4uWqjPIa-QhvxsF6hPj5J4rN3-GKD7I/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            M206
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1rlqAVW0UhKErl21npyIS1Y_jIPpp01Oy/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            M207
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1abP3e2XrYsKlWB1k50VUcqs08vMjga6C/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            M208
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1HsFl-clPDXP1JG4B_yTHQgiiBrz-8tHh/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            M209
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/12r48IVGXa6UQ0l00gsEMmwTNKDOD6ZDF/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            M210
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1iMLLfUEERhPOoqwwz7mI-bKOqfhDme5U/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            M211
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1V-ehItk6aCEx9oFCy4fxaYrJtpr5cf7L/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            M Lab BitMap
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1AZc9OcW-0HA_ixGDrNOKp6RiY3WvFCGI/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            M Lab Diseño PC
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1tqeX59vBqTVx8PwFWsXM8YbbqAKM8fcL/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            M Lab Info Basica
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <div class="col-md-6 mx-auto">
                                    
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Edificio L</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1RHKdmiibzH8lZ9NCK7Ws4nLUyQ4ACq0s/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            L105
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1xvTSWqcbD7b5G8QEeMVJpymRNKO-6hxw/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            L106
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>

                                </div>
                            </div>
                        </div>
                    </div>