                        <div class="row contenido">

                            <div class="col-12 rounded shadow-sm rounded pb-5">
                                
                                <h1 class="py-3 text-center">Horarios de Grupo 2024-2</h1>
                                <p class="py-3 text-center">
                                    Actualización 07/05/2024 21:20 p.m.
                                </p>
                                <div class="row">
                                    <div class="col-md-6 col-12">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>DDA</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1GIs4hefSos3lN62kVebcpNyXZtJHD0uV/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                DDA101
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1yplNEdykTPFO9rMa02oWW46Ky4CmABIJ/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                DDA201
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1pWKHfHhdOtf8pOkNmnso2I9uG0URsIXn/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                DDA301
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/17ZXjE2eSTs755prSJchgpDzNWSPSBZq9/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                DDA302
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1S-LcXcvi6TYyVfz4GhHZbUdcpzBSA5re/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                DDA303
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1SbnmE2stRkA8ASMve9ZDgBVOp895ITpF/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                DDA304
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>                                                
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1s9ddMAigPDac-yM7gxKs7x-W_aPrbgEK/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                DDA305 (VESPERTINO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>                                                
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1Ha-Vt28yime4qdBik1lfjGRvWTwXnOG2/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                DDA306 (VESPERTINO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>   
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1v-hfdRUoLCyVLiwrzRkzEM20InJLq9j7/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                DDA307 (VESPERTINO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>   
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1YP9y2iebjPuYqP0TAmDpAVLsKsNiruWS/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                DDA401
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>   
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/14vXueX9Nb3SihzT3xcNXxV3SMEiUEQvY/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                DDA402
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>   
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1m8wdT86bQxa9vmHiU_d8jZcN1x7ApRqw/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                DDA501
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>   
                                                <tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1XqujTLbSRu1z_mze7VUImemPbrCPyq2g/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                DDA502
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>   
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1T3LsEtykwB6V_aHkSpZNuqwsTC6nVAC5/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                DDA503 (VESPERTINO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>   

                                            </tbody>
                                        </table>
                                    </div>

                                    <div class="col-md-6 col-12">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>LDDPA</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1AmKMhf_LP4wrrTWKyIBjRw5fN8_5cKkV/view?usp=sharingk" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                LDDPA701 (VESPERTINO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1q7qyBA-dZHOfBnRdSpNmlsWktkK7UjSw/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                LDDPA702 (VESPERTINO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1DB6FtOybk-XocPoDTBnVJj2N_2Tjxkxq/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                LDDPA801 (VESPERTINO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1Q6FwVEzWMB-HfykSWhxPl6tZQVPirj45/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                LDDPA802 (VESPERTINO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1HUTKKz6xRPYwYYad355Gv1hyLMzHppUo/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                LDDPA901 (VESPERTINO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1JzHnMQlpQpeo5ZY8OtNczlKa1_UgONqZ/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                LDDPA902 (VESPERTINO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1uRVbz3lbYGi_RPgC0P0yAEsalmc9sLVD/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                LDDPA903 (VESPERTINO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1DniI--IH2mxX8u2pattrBYE1laWiZGKC/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                LDDPA904 (VESPERTINO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1V3rRSbdpfiAxVHQ2GbqoF8tVU-NixYZU/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                LDDPAE905 (EJECUTIVO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1vMZRVg_aoGLe2XZLlhzieLOEZps7er9L/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                <i class="fontGrande bx bxs-file-pdf"></i>
                                                                LDDPA1001 (VESPERTINO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>