                        <div class="row contenido">

                            <div class="col-12 rounded shadow-sm rounded pb-5">
                                
                                <h1 class="py-3 text-center">Horarios de Grupo 2024-3</h1>
                                <p class="py-3 text-center">
                                    Actualización 04/09/2024 23:20 p.m.
                                </p>
                                <div class="row">
                                    <div class="col-md-6 col-12">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>DAD y DDA</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1691qkPEq-7MKbCyKeu7dKs7b5P492uL0/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD101
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1fICnSjZR8XvefUPFcjt-a8RJXT2NR-qz/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD102
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1znrtx1OUfOppMTUQnGE9axrWaYK0TFnG/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD103
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1MMDH-zMjOdqg3Ake-hhr03-72CbxhkiO/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD104
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1QTlbNcEWZ17B_i3AW2LkCiAIam5phWG8/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD105 (VESPERTINO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1wlcsW59CEjIXhvRBPJnIMAVPzSI33lPd/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD106 (VESPERTINO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1gZFpwLguWWpEN5Z8LrmKu-emd9Rke7iP/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD107 (VESPERTINO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1xkpU6rt9svce1WQDXMo02WUtWcNY_fmj/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD108 (VESPERTINO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1GnMhqQtSgVVsVgcU8LG42K5wmQBgZpzE/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DAD109 (VESPERTINO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1c4ntZwA0Vg3zbghVTysxHFCatsqSrm6k/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DDA201
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1dxb1ub51FfRJzXrLrHqOtl5ZtvicbaBI/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DDA301
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/13b1N4d13779WG78lUIfo6tg-wpMbE6qx/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DDA401
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1dU9_eLKpoHkMLx_5UeZ7OThKdt30oFVQ/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DDA402
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1i2Jm_0VUjfCOfy_0Dw0rV56ZRqmFHDI9/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DDA403
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/159ycXBFEKQFVSJMGQV95eoisBlRvX19x/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DDA404 (VESPERTINO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1lvMg-Bzbn0MDHJxkaivtjbJ1_fvOFC46/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DDA405 (VESPERTINO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1Qh1nuU85vgObtv3uDnEyEXWJWrz4gLK7/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    DDA501
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>

                                    <div class="col-md-6 col-12">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>LDDPA</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/13dGredDPNl4jqOQdAdmT8gKHA687SzaI/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPA701 (VESPERTINO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1Vfj6hrKMv5MyApj5QpjvDJN7zJWDGEZo/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPA702 (VESPERTINO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1evbkc5UKOPDD9h0f8oBbGklpoziehYL1/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPA703 (VESPERTINO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1hf8NuIdBJmJ4eW2LQslq9zHkpKvpTEHH/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPAE704 (EJECUTIVA)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1uhK-Mlq7iD2tmoI9ljAxoBDhQyZk_U4H/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPA801 (VESPERTINO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/19_HBt9C_SI2-zjvYfexe1rbyJPYL-vvD/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPA901 (VESPERTINO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1QTJfhw8Z0yt1dIwYuZ3R-BWnVCv-kErU/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPA1001 (VESPERTINO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/165MAtX7WHNfOx1L5eZqxpdSzlP0Mh4-S/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPA1002 (VESPERTINO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1_vvxBqFXXre4hu0gkAT1jJRREnpz4djt/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPA1003 (VESPERTINO)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div class="liLinks my-1">
                                                            <a href="https://drive.google.com/file/d/1_XOiXoMdqv1rXGqwTb4Feop-iFZMJ__n/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                                                <div class="centrado-v">
                                                                    <i class="fontGrande bx bxs-file-pdf"></i>
                                                                    LDDPAE1004 (EJECUTIVA)
                                                                </div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>