                    <div class="row contenido">

                        <div class="col-12 rounded shadow-sm rounded pb-5 mt-5" style="text-align: center;">
                            <h1>DIVISIÓN ACADÉMICA DE</h1>
                            <h1>Diseño, Redes e Inteligencia Artificial</h1>
                            <br>
                            <p style="text-align: center;">
                                Atención: <a href="mailto:dirac.procesproduc@utfv.edu.mx"><b>dirac.procesproduc@utfv.edu.mx</b></a>
                                <br>
                                Tel: <a href="tel:+525536409503"><b>55-364-09-503 Ext: 255</b></a> 
                                Whats: <a href="https://api.whatsapp.com/send?phone=5632179952"><b>56-32-17-99-52</b></a>
                                
                            </p>
                            <br>
                            <br>
                        </div>
                        
                        <br>
                        <br>

                        <div class="col-12 rounded shadow-sm rounded pb-5 mt-5">
                            <br>
                            <br>
                            
                            <h1 style="text-align: center;">BIENVENIDOS</h1>
                            <br>
                            <p>
                                Estimados estudiantes, les damos la más cordial bienvenida a este nuevo ciclo escolar que comenzamos en la Universidad Tecnológica Fidel Velázquez . El día de hoy iniciamos juntos una nueva etapa de nuestra vida llena de conocimientos, aprendizajes, experiencias, alegrías y curiosidades. Que este año sea de muchos éxitos.
                                <br>
                                <br>
                                Agradecemos la confianza y compromiso
                                <br>
                                <br>
                                <div style="text-align: center;">
                                    <h5>A T E N T A M E N T E</h5>
                                    <br>
                                    <h5>LA DIVISIÓN ACADÉMICA DE PROCESOS DE PRODUCCIÓN</h5>
                                </div>

                                <div class="row">
                                    <div class="col-md-3"></div>
                                    <div class="col-md-6">
                                        <img src="img/logoDisenoDigital.jpg" class="img-fluid" alt="Logo Diseño Digital UTFV">
                                    </div>
                                    <div class="col-md-3"></div>
                                </div>
                                
                            </p>
                            <br>
                            <br>
                        </div>
                        
                        <br>
                        <br>
                        
                        <div class="col-12 rounded shadow-sm rounded pb-5 mt-5">
                            <h2>Calendario Escolar 2024-2025</h2>
                            <br>
                            <a href="https://drive.google.com/file/d/1iCKKXq87VLQNj3DrCfn81XK3Yq9Z5J0i/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                <img src="img/calendario2024.jpg" class="img-fluid" alt="Calendario Escolar">
                            </a>
                            <br>
                            <br>
                        </div>
                    </div>