                    <div class="row contenido">

                        <div class="col-12 rounded shadow-sm rounded pb-5 mt-5" style="text-align: center;">
                            <h1>DIVISIÓN ACADÉMICA DE</h1>
                            <h1>Diseño, Redes e Inteligencia Artificial</h1>
                            <br>
                            <p style="text-align: center;">
                                Atención: <a href="mailto:dirac.procesproduc@utfv.edu.mx"><b>dirac.procesproduc@utfv.edu.mx</b></a>
                                <br>
                                Tel: <a href="tel:+525536409503"><b>55-364-09-503 Ext: 255</b></a> 
                                Whats: <a href="https://api.whatsapp.com/send?phone=5632179952"><b>56-32-17-99-52</b></a>
                                
                            </p>
                            <br>
                            <br>
                        </div>
                        
                        <br>
                        <br>

                        <div class="col-12 rounded shadow-sm rounded pb-5 mt-5">
                            <br>
                            <br>
                            
                            <h1 style="text-align: center;">BIENVENIDOS</h1>
                            <br>
                            <p>
                                Estimados estudiantes, les damos la más cordial bienvenida a este nuevo ciclo escolar que comenzamos en la Universidad Tecnológica Fidel Velázquez . El día de hoy iniciamos juntos una nueva etapa de nuestra vida llena de conocimientos, aprendizajes, experiencias, alegrías y curiosidades. Que este año sea de muchos éxitos.
                                <br>
                                <br>
                                Agradecemos la confianza y compromiso
                                <br>
                                <br>
                                <div style="text-align: center;">
                                    <h5>A T E N T A M E N T E</h5>
                                    <br>
                                    <h5>LA DIVISIÓN ACADÉMICA DE PROCESOS DE PRODUCCIÓN</h5>
                                </div>

                                <div class="row">
                                    <div class="col-md-3"></div>
                                    <div class="col-md-6">
                                        <img src="img/logoDisenoDigital.jpg" class="img-fluid" alt="Logo Diseño Digital UTFV">
                                    </div>
                                    <div class="col-md-3"></div>
                                </div>
                                
                            </p>
                            <br>
                            <br>
                        </div>
                        
                        <br>
                        <br>

                        <div class="col-12 rounded shadow-sm rounded pb-5 mt-5"></div>
                        <br>
                            <h1>Becas para el Bienestar por Aprovechamiento Académico</h1>
                            <p>para el ciclo 2024-2025. Este programa busca apoyar a estudiantes regulares con un promedio mínimo de 8.5 y cuyos ingresos familiares estén por debajo de la línea de bajos recursos. Se otorgará un apoyo económico mensual de $800.00, sujeto a disponibilidad presupuestal. Los interesados deben registrarse electrónicamente entre el 14 y el 18 de octubre de 2024, cumpliendo con requisitos específicos, como presentar documentos que acrediten su situación académica y económica. Los resultados se publicarán del 27 al 29 de noviembre de 2024, y los beneficiarios deberán imprimir el dictamen de asignación. Es importante que los solicitantes mantengan actualizada su información de contacto y cumplan con todos los requisitos para evitar la cancelación de la beca.</p>
                            <br>
                            <a href="https://drive.google.com/file/d/18oklssgQL4GyG_Z7l3CATK3XhDJUFlze/view?usp=sharing">
                                <img src="img/BannerBeca.jpg" class="img-fluid" alt="Calendario Escolar">
                            </a>
                            <br>
                            <br>
                        </div>
                        <br>
                        <br>
                        
                        <div class="col-12 rounded shadow-sm rounded pb-5 mt-5">
                            <h2>Calendario Escolar 2024-2025</h2>
                            <br>
                            <a href="https://drive.google.com/file/d/1iCKKXq87VLQNj3DrCfn81XK3Yq9Z5J0i/view?usp=drive_link" target="_blank" rel="noopener noreferrer">
                                <img src="img/calendario2024.jpg" class="img-fluid" alt="Calendario Escolar">
                            </a>
                            <br>
                            <br>
                        </div>
                    </div>