                    <div class="row contenido">

                        <div class="col-12 rounded shadow-sm rounded pb-5">
                            
                            <h1 class="py-3 text-center">Listas de Grupo 2024-3</h1>
                            <p class="py-3 text-center">
                                Actualización 30/08/2024 20:26 p.m.
                            </p>
                            <div class="row">

                                <div class="col-md-6 col-12">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Listas Previas 2024-3</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div class="liLinks my-1">
                                                        <a href="https://drive.google.com/file/d/1skaGPuq3UxqeHpBZRz-eBHWoLV1T6BLp/view?usp=sharing" target="_blank" rel="noopener noreferrer">
                                                            <div class="centrado-v">
                                                            <i class="fontGrande bx bxs-file-pdf"></i>
                                                            Listas preliminares DAD, DDA y LDDPA
                                                            </div>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>  

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>